name: build

on: [ push ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up CMake
        run: |
          brew update
          brew install cmake

      - name: Build Congestion Unaware Test
        run: |
          cd test
          cmake -S . -B build -DBUILDTARGET="congestion_aware" -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --config Debug -j $(nproc)

      - name: Test
        run: |
          cd test/build
          ctest --config Debug --output-on-failure
